### PR TITLE
removed the f9 shortcut to sort all lines in a pad

### LINKED ISSUE #813: Pressing F9 destroys everything
**Description**
In editor, when pressing F9 key by accident, all lines are mixed up. Fortunately this can be undone.

**To Reproduce**
1. Open new note
2. Type a few lines, possibly "---" separators
3. Press F9
4. See error --> text lines are scrambled

**Expected behavior**
Nothing should happen.

### PR DESCRIPTION
**Pull request by DerMolly**
### Component/Part
editor

### Description
This PR removes the f9 shortcut to sort all lines in a pad

### Steps

- [x] Added implementation
- [x] Extended changelog
- [x] I read the [contribution documentation](https://github.com/hedgedoc/react-client/blob/main/CONTRIBUTING.md) and signed-off my commits to accept the DCO.

### Related Issue(s)
fixes #813

### CODE REVIEW

**Comment by davidmehren** [comment]
I can confirm that pressing F9 now does nothing!

**Review by davidmehren — APPROVED** [review]

File: src/components/editor/editor-pane/key-map.ts [hunk 1]
```diff
@@ -16,6 +16,7 @@ import {
 
 const isVim = (keyMapName?: string) => (keyMapName?.substr(0, 3) === 'vim')
 
+const pass = (_: Editor): void | typeof Pass => undefined
```
Comment (ErikMichelson) [inline src/components/editor/editor-pane/key-map.ts:19]: This function has the same signature as `suppressSave` and is therefore redundant code. Consider merging both functions into one.

**Review by ErikMichelson — CHANGES_REQUESTED** [review]

File: src/components/editor/editor-pane/key-map.ts (hunk 1 above)
Comment (DerMolly) [reply src/components/editor/editor-pane/key-map.ts]: done

**Review by mrdrogdrog — APPROVED** [review]

**Review by ErikMichelson — APPROVED** [review]
